# Generated by Django 3.2.3 on 2021-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_applicants_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='aplicant',
            field=models.ManyToManyField(related_name='_interview_session_aplicant_+', to='interview.Applicants'),
        ),
    ]
