# Generated by Django 3.2.3 on 2021-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_session_aplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='session',
        ),
        migrations.AlterField(
            model_name='session',
            name='aplicant',
            field=models.ManyToManyField(to='interview.Applicants'),
        ),
    ]
