# Generated by Django 3.2.3 on 2021-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20210529_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='session',
            field=models.ManyToManyField(to='interview.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='aplicant',
            field=models.ManyToManyField(related_name='_interview_session_aplicant_+', to='interview.Applicants'),
        ),
    ]
